version: "3.8"

services:
  poshagam-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poshagam-client
    restart: unless-stopped
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - VITE_API_URL=http://194.34.239.189:8080/api
      # - VITE_API_URL=https://poshagam.shop/api
      - VITE_REFRESH_TOKEN=poshagam_refresh_token_rafaello
    networks:
      - poshagam-network

networks:
  poshagam-network:
    driver: bridge
